name = "1 . 21 . 1 Terratonic"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb920d46f0087d14677b646b4a29c7210136a480c9a94e66d8008e5bf05a66fa"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.170"
