name = "1 . 21 . 1 Terratonic"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7cbf4a70e7119d8525b72cc9a1add591bca1db58ef6e3a4e69205fc49f645713"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.170"
