name = "1 . 21 . 1 Terratonic"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0faf9ee50d930fafea8d0619a1fe05b69459f64cd39ef71aa6651b354962b1e4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.170"
