name = "1 . 21 . 1 Terratonic"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2f65cbc12db8e3f8cbea4ebba439f8c5f958b197ced81496c5d1b60361e352f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.170"
