name = "1 . 21 . 1 Terratonic"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31e1e57f7c963b8f438693823369eee23e5e4848acaf2246a99b10ada36d8b73"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.170"
