name = "1 . 21 . 1 Terratonic"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18156af8dd71197405a5a54925a86a38cad86bc73e1ea6cd538961d5487a05fc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.170"
