name = "1 . 21 . 1 Terratonic"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c8511abf12e570e51ed25b69ea912d6fc1561bb71adca5f0c1c52101e201955"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.170"
