name = "1 . 21 . 1 Terratonic"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3237027a8efca2d4ec23998094cc191af2ca1e561e266bc334e0c9ed62923060"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.170"
