name = "1 . 21 . 1 Terratonic"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f11abe36218a2428dd855f80b2fdec3ca351107e6eb69cd6fa25c2cec2285ab"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.170"
