name = "1 . 21 . 1 Terratonic"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c9a751b68e681763fd94f0f4962c7eaeb080a4f4b6c90a9eaa6a8900272e46a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.170"
