name = "1 . 21 . 1 Terratonic"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fef6c449470a5b52e4b2339096d697aefd35386cfc9628d28d129c80b7676cf4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.170"
