name = "1 . 21 . 1 Terratonic"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "76cb274e4374e6433cd9fc947dd1160c5e29b36dd3849463ec0820579789120c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.170"
