name = "1 . 21 . 1 Terratonic"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ff4bc4f5a76e3cc7dfe03ef90f85f02dc963eeef49a88d0d743fa7540b41bf8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.170"
