name = "1 . 21 . 1 Terratonic"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bb9cbffae1036b02d7bc50bda855aa3ef66a3936b1677654110611ba4230fa9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.170"
