name = "1 . 21 . 1 Terratonic"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe9c9d1254d5e101ae0e74622fd04957c91d7ac4b74fa9ed8d1ef0bfb3bd9742"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.170"
