name = "serverpack3"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b8909672740afccc690debc75b1481a4a387fa49d9df23a96340b533a48b4ed"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
