name = "serverpack3"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2424337b7bd817ca36784d7deb7b3b55f42e5532ebed3bc50890de04313c06d"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
