name = "serverpack3"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a9f94916e3181475cd1fc812833f17f5f0b1964f19a725adfc90bcee4daf452"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
