name = "serverpack3"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31be7d82aae19db8b1b78b1ee4a49c099cddb6e9d219dc35dcf15f3a8f2a495d"

[versions]
forge = "43.3.0"
minecraft = "1.19.2"
