name = "1.21.5 Big Globe Server"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2814beb5fb5d6765bab417376cbaae91fc5a483511170d1e6e0f80b0284e183b"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
