name = "Orespawn"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83c886419c32965d01c62644ed4192ae8d10bd5957415dae2d01eefc20c6d550"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
