name = "Orespawn"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9739d06e503b1c86d33b3e5670d1db433244fecbd3a10171b6249537ecd0c085"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
