name = "Create Aero"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29fb82c5ec1ab635d51e56eca979d95faee614dcc981b1e08b15fd4dc2bdd8ac"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
