name = "Create Aero"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a11d2f4245d6a4ffa724d40b0f6483116be67201f2d687cd9c99e6ef68316b68"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
