name = "Create Aero"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad211abc822333882d3981d475ed0387d4467e39276d8dd584402f21a2c9d90a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
