name = "Normal Minecraft"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb97782690e6473c6d20e2094d888d9d3f2c960f9cf7569b12a79a9176e1c45a"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
