name = "Normal Minecraft"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f517084ac87c2eb28252abc2a920bffb25c27574a1f47be19575cc3416b9ffda"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
