name = "Normal Minecraft"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60479c20243520251aeb97f0e0a68b5b1723494698d82f1773b4e816c46103e3"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
