name = "Pixelmon Create"
author = "grainsoup"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02c1faff05a9b47b7a0ac2381aad4f803bd83390c63e74c0a0c4458a621ee041"

[versions]
forge = "36.2.34"
minecraft = "1.16.5"
